module.exports = {
    defaultFlag: { minLength: 1, maxLength: Infinity, name: "--uri" },
    "--uri": { minLength: 1, maxLength: 1, multi: true },
    "--head": { minLength: 0, maxLength: 0 },
    "-I": { minLength: 0, maxLength: 0 },
    "--location": { minLength: 0, maxLength: 0 },
    "--proxy": { minLength: 1, maxLength: 1 },
    "--data": { minLength: 1, maxLength: 1, multi: true },
    "-X": { minLength: 1, maxLength: 1 },
    "-H": { minLength: 1, maxLength: 1, multi: true },
    "-o": { minLength: 1, maxLength: Infinity, multi: true },
    "-u": { minLength: 1, maxLength: 1 },
    "--form": { minLength: 1, maxLength: 1, multi: true },
    "--urlEncode": { minLength: 0, maxLength: 0 },
    "--session": { minLength: 0, maxLength: 0 },
    "--tls": { minLength: 1, maxLength: 1 },
    "--tcp": { minLength: 1, maxLength: 1 },
    "--udp": { minLength: 1, maxLength: 1 },
    "--ssh": { minLength: 1, maxLength: 1 },
    "--noProxy": { minLength: 0, maxLength: 0 },
    "--dns": { minLength: 0, maxLength: 0 },
    "--getDns": { minLength: 0, maxLength: 0 },
    "--dnsServers": { minLength: 1, maxLength: Infinity },
    "--lookup": { minLength: 1, maxLength: Infinity },
    "-k": { minLength: 0, maxLength: 0 },
    "--resolve": { minLength: 1, maxLength: 1, multi: true },
    "--referer": { minLength: 1, maxLength: 1 },
    "--user-agent": { minLength: 1, maxLength: 1 },
    "--cookie": { minLength: 1, maxLength: 1, multi: true },
    "--cacert": { minLength: 1, maxLength: 1, multi: true },
    "-v": { minLength: 0, maxLength: 0 },
    "--connect": { minLength: 0, maxLength: 0 },
    "--exec": { minLength: 1, maxLength: 1 },
    "--getHeaders": { minLength: 0, maxLength: 0 }
};
